### ISSUE TITLE
Any example using http_worker with Authorization header

### ISSUE THREAD

**Issue by sonecabr** [satori-com/mzbench#117]
Hi guys, 
Sorry for open an issue but I cant find other channel or forum to ask. Do you have a doc or tutorial with any examples to send a request (I am used http_worker) with Authorization header and https by using the dsl? 
Thanks, and sorry again. Fell free to send me a link to docs or forum and close this issue if you understand I cant ask here.

**Comment by parsifal-47** [comment]
Hi,
thanks for asking, it is completely not a problem, sorry for late response.
We don't have exact example with the worker, but most probably @timofey-barmin has one

**Comment by parsifal-47** [comment]
sorry for delay, for basic auth, you probably could use non-base64 encoded in a following way:

```
#!benchDL
make_install(git = "https://github.com/machinezone/mzbench.git",
             dir = "workers/http")

pool(size = numvar("conn_count", 20),
     worker_start = linear(10 rps),
     worker_type = http_worker):

     connect(var("host", "172.21.3.3"), numvar("port", 80))
     set_options("Authorization" = "Basic user:password")
     loop(time = 60 sec,
             rate = ramp(linear, 1 rps, numvar("max_rps", 2000) rps)):
            get(var("endpoint", "/index.html"))
```

for HTTPS support, we currently don't have it, there is an experimental branch
https://github.com/machinezone/mzbench/tree/ridrisov/https-worker
but if you could use stunnel, that's better because I remember some stability issues there.

Let me know if you have more questions or something doesn't work for you
