### ISSUE TITLE
Distribution of a prebuilt external worker to nodes

### ISSUE THREAD

**Issue by Galhad** [satori-com/mzbench#158]
Hi, I have a question to which I couldn't find an answer in the documentation:

I have a prebuilt tarball of an external worker. It has been copied to the `tgz_packages_dir` directory (in my case `/home/mzbench/.local/cache/mzbench_api/packages/name.tgz`). Is there a way to distribute it to the nodes?

Maybe there is another, more proper way to do this? What I want to accomplish is to build the worker once.

**Comment by parsifal-47** [comment]
Hi Galhad,
the idea is that system does that for you implicitly, we thought that a user don't need to control this as far as system works properly.
But, there is an option for that, if you disable:
`custom_os_code_builds` and `auto_update_deployed_code`
it will use the tarball for any worker OS and won't try to update/rebuild it.

Once you enable it and try to run, check logs for error messages because it will contain the information on where API server is trying to look for the archive.

Please let me know if you have any follow-up questions,
thanks!

**Comment by Galhad** [comment]
It worked, thank you very much!
